/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { MeasurementUnit } from './measurementUnit';


   export interface Ingredient {
    id: number;
    name?: string;
    qty?: number;
    unit?: MeasurementUnit;
}
