/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type MeasurementUnit = 'teaspoon'
| 'tablespoon'
| 'fluid-ounce'
| 'cup'
| 'pint'
| 'quart'
| 'gallon'
| 'milliliter'
| 'liter'
| 'deciliter'
| 'pound'
| 'ounce'
| 'milligram'
| 'gram'
| 'kilogram';

export const MeasurementUnit = {
    Teaspoon: 'teaspoon' as MeasurementUnit,
    Tablespoon: 'tablespoon' as MeasurementUnit,
    FluidOunce: 'fluid-ounce' as MeasurementUnit,
    Cup: 'cup' as MeasurementUnit,
    Pint: 'pint' as MeasurementUnit,
    Quart: 'quart' as MeasurementUnit,
    Gallon: 'gallon' as MeasurementUnit,
    Milliliter: 'milliliter' as MeasurementUnit,
    Liter: 'liter' as MeasurementUnit,
    Deciliter: 'deciliter' as MeasurementUnit,
    Pound: 'pound' as MeasurementUnit,
    Ounce: 'ounce' as MeasurementUnit,
    Milligram: 'milligram' as MeasurementUnit,
    Gram: 'gram' as MeasurementUnit,
    Kilogram: 'kilogram' as MeasurementUnit
};
