/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { Ingredient } from './ingredient';
   import { ServingSize } from './servingSize';
   import { Step } from './step';


   export interface NewRecipe {
    name: string;
    description?: string;
    serves?: number;
    servingSize?: ServingSize;
    ingredients?: Array<Ingredient>;
    method?: Array<Step>;
    created?: Date;
    lastModified?: Date;
    src?: string;
    tags?: Array<string>;
    links?: Array<string>;
}
