/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StepDetails {
    number?: number;
    description?: string;
}
