/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { StepDetails } from './stepDetails';
   import { StepTime } from './stepTime';


   export interface Step {
    section?: number;
    stepTime?: StepTime;
    stepDetails?: Array<StepDetails>;
}
