/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TimeUnit = 'second' | 'minute' | 'hour' | 'day' | 'week' | 'year';

export const TimeUnit = {
    Second: 'second' as TimeUnit,
    Minute: 'minute' as TimeUnit,
    Hour: 'hour' as TimeUnit,
    Day: 'day' as TimeUnit,
    Week: 'week' as TimeUnit,
    Year: 'year' as TimeUnit
};
