swagger: "2.0"
info:
  description: Type definitions for the recipe book API
  version: 1.0.0
definitions:  
  ServerInfo:
    type: object
    properties:
      name:
        type: string
      description:
        type: string
      version:
        type: string
      uptime:
        type: number
  Recipe:
    type: object
    properties: 
      uid:
        type: number
      name:
        type: string
      description:
        type: string
      ingredients:
        type: array
        items:
          $ref: '#/definitions/Ingredient'
      method:
        type: array
        items:
          $ref: '#/definitions/Step'
      created:
        type: string
      lastModified:
        type: string
      src:
        type: string
      tags:
        type: array
        items: 
          type: string
      links:
        type: array
        items:
          type: string
  Ingredient:
    type: object
    properties:
      name: 
        type: string
      qty:
        type: number
      unit:
        type: object
        properties:
          uid: 
            type: number
          name: 
            type: string
          metric:
            type: boolean
  Step:
    type: object 
    properties:
      section:
        type: number
      time:
        type: number
      steps:
        type: array
        items:
          type: object
          properties:
            step:
              type: number
            description:
              type: string
            
        