swagger: "2.0"
info:
  description: API for the Bee Book recipe book application
  version: 1.0.0
  title: Bee Book API
basePath: "/api/v1"
paths:
  /ping:
    get:
      tags:
        - "root"
      summary: "Get server information"
      operationId: "ping"
      produces:
        - "application/json"
      responses:
        200:
          description: "success"
          schema:
            $ref: "#/definitions/ServerInfo"
definitions:
  ServerInfo:
    type: "object"
    properties:
      name:
        type: "string"
      description:
        type: "string"
      version:
        type: "string"
      uptime:
        type: "number"
