/**
 * Racipe Book
 * An API for
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yourmom@yourmom.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { NewRecipeLog } from '../model/newRecipeLog';
import { RecipeLog } from '../model/recipeLog';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';


@Injectable()
export class RecipeLogService {

    protected basePath = 'http://localhost:8080/RecipeBook/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * Creates a new recipe log in the book.
     * @param body Recipe Log to add to the book
     * @param recipeId ID of recipe for which a log will be created
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addRecipeLog(body: NewRecipeLog, recipeId: number, observe?: 'body', reportProgress?: boolean): Observable<RecipeLog>;
    public addRecipeLog(body: NewRecipeLog, recipeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecipeLog>>;
    public addRecipeLog(body: NewRecipeLog, recipeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecipeLog>>;
    public addRecipeLog(body: NewRecipeLog, recipeId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addRecipeLog.');
        }

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling addRecipeLog.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<RecipeLog>(`${this.basePath}/recipes/${encodeURIComponent(String(recipeId))}/logs`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * deletes a single recipe log based on the ID supplied
     * @param recipeId ID of recipe to which the log belongs
     * @param logId ID of recipe log to be deleted
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteRecipeLog(recipeId: number, logId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteRecipeLog(recipeId: number, logId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteRecipeLog(recipeId: number, logId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteRecipeLog(recipeId: number, logId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling deleteRecipeLog.');
        }

        if (logId === null || logId === undefined) {
            throw new Error('Required parameter logId was null or undefined when calling deleteRecipeLog.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/recipes/${encodeURIComponent(String(recipeId))}/logs/${encodeURIComponent(String(logId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Get a specific log for a specific recipe
     * @param recipeId ID of recipe to which the log belongs
     * @param logId ID of recipe log to be fetched
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLogForRecipeByLogId(recipeId: number, logId: number, observe?: 'body', reportProgress?: boolean): Observable<RecipeLog>;
    public getLogForRecipeByLogId(recipeId: number, logId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RecipeLog>>;
    public getLogForRecipeByLogId(recipeId: number, logId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RecipeLog>>;
    public getLogForRecipeByLogId(recipeId: number, logId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling getLogForRecipeByLogId.');
        }

        if (logId === null || logId === undefined) {
            throw new Error('Required parameter logId was null or undefined when calling getLogForRecipeByLogId.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<RecipeLog>(`${this.basePath}/recipes/${encodeURIComponent(String(recipeId))}/logs/${encodeURIComponent(String(logId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * Get all of the logs for a specific recipe
     * @param recipeId ID of recipe for which logs are to be fetched
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLogsForRecipe(recipeId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<RecipeLog>>;
    public getLogsForRecipe(recipeId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<RecipeLog>>>;
    public getLogsForRecipe(recipeId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<RecipeLog>>>;
    public getLogsForRecipe(recipeId: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (recipeId === null || recipeId === undefined) {
            throw new Error('Required parameter recipeId was null or undefined when calling getLogsForRecipe.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<RecipeLog>>(`${this.basePath}/recipes/${encodeURIComponent(String(recipeId))}/logs`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
